version: '3.8'
services:
  nexrad-ingestor-service:
    image: vulcans/nexrad-ingestor-service:latest
    container_name: nexrad-ingestor-service
    build:
      context: ingestor_service
    networks:
      - vulcan-network

  merra-ingestor-service:
    image: vulcans/merra-ingestor-service:latest
    container_name: merra-ingestor-service
    networks:
      - vulcan-network

  db-user-history:
    image: 'postgres:13.1-alpine'
    container_name: db-user-history
    restart: always
    ports:
      - 5432:5432
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_user_history
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vulcan-network

  user-history-service:
    image: vulcans/kafka-user-history:linux
    container_name: user-history-service
    depends_on:
      db-user-history:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_HOST=db-user-history
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DATABASE=db_user_history
      - SPRING_KAFKA_HOST=kafka
      - SPRING_KAFKA_PORT=9092
    networks:
      - vulcan-network

  db-user-management:
    image: 'postgres:13.1-alpine'
    container_name: db-user-management
    restart: always
    ports:
      - 5433:5432
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_user_management
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vulcan-network

  user-management-service:
    image: vulcans/kafka-user-management:linux
    container_name: user-management-service
    depends_on:
      db-user-management:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_HOST=db-user-management
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DATABASE=db_user_management
      - SPRING_KAFKA_HOST=kafka
      - SPRING_KAFKA_PORT=9092
    networks:
      - vulcan-network

  api-gateway:
    image: vulcans/api-gateway:latest
    container_name: api-gateway
    build:
      context: api_gateway
    depends_on:
      - nexrad-ingestor-service
      - user-history-service
      - user-management-service
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    networks:
      - vulcan-network

  weather-forecast-ui:
    image: vulcans/weather-forecast-ui
    container_name: weather-forecast-ui
    ports:
      - 5000:8080
    environment:
      NODE_ENV: production

networks:
  vulcan-network:
    name: vulcan
