version: '3.8'
services:
  nexrad-ingestor-service:
    image: vulcans/nexrad-ingestor-service
    container_name: nexrad-ingestor-service
    build:
      context: .
    ports:
      - 12552:8080
    networks:
      - vulcan-network

networks:
  vulcan-network:
    name: vulcan
