version: '3.8'
services:
  http-api-gateway:
    container_name: http-api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    networks:
      - vulcan-network

networks:
  vulcan-network:
    name: vulcan
