version: '3.8'
services:
  api-gateway:
    image: vulcans/api-gateway
    container_name: api-gateway
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    networks:
      - vulcan-network

networks:
  vulcan-network:
    name: vulcan
