version: '3.8'
services:
  http-api-gateway:
    image: vulcans/http-api-gateway
    container_name: http-api-gateway
    build:
      context: ./
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    networks:
      - vulcan-network

networks:
  vulcan-network:
    name: vulcan
