apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexrad-ingestor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app : nexrad-ingestor
  template:
    metadata:
      name: nexrad-ingestor
      labels:
        app: nexrad-ingestor
    spec:
      containers:
        - name: nexrad-ingestor
          ports:
            - containerPort: 8080
              name: nexrad-ingestor
          image: vulcans/nexrad-ingestor-service:latest
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nexrad-ingestor-service
spec:
  selector :
    app : nexrad-ingestor
  type: ClusterIP
  ports:
    - protocol : "TCP"
      port: 8080
