version: '3.8'
services:
  merra-ingestor-service:
    image: vulcans/merra-ingestor-service
    container_name: merra-ingestor-service
    build:
      context: ./
    ports:
      - 12553:3000
    networks:
      - vulcan-network

networks:
  vulcan-network:
    name: vulcan
