version: '3.8'
services:
  merra-ingestor-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: merra-ingestor-service
    ports:
      - 12553:8080
    networks:
      - vulcan-network


networks:
  vulcan-network:
    name: vulcan
