apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-forecast
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app : http-forecast
  template:
    metadata:
      name: http-forecast
      labels:
        app: http-forecast
    spec:
      containers:
        - name: http-forecast
          ports:
            - containerPort: 8080
              name: http-forecast
          image: vulcans/http-forecast-service:latest
---
apiVersion: v1
kind: Service
metadata:
  name: http-forecast-service
spec:
  selector :
    app : http-forecast
  type: ClusterIP
  ports:
    - protocol : "TCP"
      port: 8080