apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app : user-management
  template:
    metadata:
      name: user-management
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: hostname-config
                  key: postgres_host
            - name: SPRING_DATASOURCE_DATABASE
              value: db_user_management
          ports:
            - containerPort: 8080
              name: user-management
          image: vulcans/user-management:2.2
---
apiVersion: v1
kind: Service
metadata:
  name: user-management
spec:
  selector :
    app : user-management
  type: NodePort
  ports:
    - protocol : "TCP"
      port: 80
      targetPort : 8080
      nodePort: 31000
