name: API Gateway Service CI

on:
  workflow_dispatch:
  push:
    branches: [ api-gateway ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        with:
          ref: 'api-gateway'
        
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        working-directory: ./api_gateway
        run: npm install
