name: ci-ingestor-merra

on:
  push:
    branches: [develop-ingestor-merra]
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            SERVER_ADDRESS=${{ secrets.MERRA_SERVER }}
            USER_NAME=${{ secrets.MERRA_USER }}
            PASSWORD=${{ secrets.MERRA_PASSWORD_A }}
          file: ./merra_ingestor_service/Dockerfile
          push: true
          tags: vulcans/merra-ingestor-service:latest 

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
