version: '3'
services:
  postgres-service:
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_user_management
    container_name: postgres-service
  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-service
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_HOST=postgres-service
      - SPRING_DATASOURCE_PORT=5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DATABASE=db_user_management
    container_name: user-management-service
